# Generated by Django 2.0 on 2024-12-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0010_auto_20241214_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
