# Generated by Django 2.0 on 2025-01-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0027_auto_20250101_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='animaldetectapp.ForestStation'),
            preserve_default=False,
        ),
    ]
