# Generated by Django 2.0 on 2025-01-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0031_auto_20250106_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ip',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
