# Generated by Django 2.0 on 2024-12-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0006_auto_20241213_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='photo',
            field=models.ImageField(upload_to='media/animals/'),
        ),
    ]
