# Generated by Django 2.0 on 2024-12-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0007_auto_20241213_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='photo',
            field=models.ImageField(upload_to='animals/'),
        ),
    ]
