# Generated by Django 2.0 on 2024-12-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0011_auto_20241217_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='forestdivision',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
