# Generated by Django 2.0 on 2024-12-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0013_foreststation'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreststation',
            name='password',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
