# Generated by Django 2.0 on 2024-12-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0015_auto_20241220_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreststation',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaldetectapp.ForestDivision'),
        ),
    ]
