# Generated by Django 2.0 on 2024-12-21 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0016_auto_20241221_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreststation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foreststation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
