# Generated by Django 2.0 on 2024-12-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0017_auto_20241221_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreststation',
            name='login',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='animaldetectapp.Login'),
            preserve_default=False,
        ),
    ]
