# Generated by Django 2.0 on 2024-12-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0018_foreststation_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
    ]
