# Generated by Django 2.0 on 2024-12-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0025_auto_20241228_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StationAnimal',
            new_name='Station_Animal',
        ),
    ]
