# Generated by Django 2.0 on 2025-01-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animaldetectapp', '0030_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaldetectapp.Animals')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerts',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaldetectapp.Camera'),
        ),
    ]
